add a missing port to SmartNodes
akash client needs the port:

Error: post failed: Post "https://rpc.akash.smartnodes.co": dial tcp: address rpc.akash.smartnodes.co: missing port in address